//事业部维度报表
export const BUSINESS_DEPART_REPORT_REQUESTED = 'department/BUSINESS_DEPART_REPORT_REQUESTED';
export const BUSINESS_DEPART_REPORT_SUCCEEDED = 'department/BUSINESS_DEPART_REPORT_SUCCEEDED';
export const BUSINESS_DEPART_REPORT_FAILED = 'department/BUSINESS_DEPART_REPORT_FAILED';

export default{
  BUSINESS_DEPART_REPORT_REQUESTED,
  BUSINESS_DEPART_REPORT_SUCCEEDED,
  BUSINESS_DEPART_REPORT_FAILED,
}
