//事业部维度报表
export const GROUP_REPORT_REQUESTED = 'GROUP_REPORT_REQUESTED';
export const GROUP_REPORT_SUCCEEDED = 'GROUP_REPORT_SUCCEEDED';
export const GROUP_REPORT_FAILED = 'GROUP_REPORT_FAILED';

export default{
  GROUP_REPORT_REQUESTED,
  GROUP_REPORT_SUCCEEDED,
  GROUP_REPORT_FAILED
}
