//军团维度报表
export const LEGION_REPORT_REQUESTED = 'legion/LEGION_REPORT_REQUESTED';
export const LEGION_REPORT_SUCCEEDED = 'legion/LEGION_REPORT_SUCCEEDED';
export const LEGION_REPORT_FAILED = 'legion/LEGION_REPORT_FAILED';

export default{
  LEGION_REPORT_REQUESTED,
  LEGION_REPORT_SUCCEEDED,
  LEGION_REPORT_FAILED,
}
